title: Learning Images
description: A starter guide for Image Processing and CV
theme: just-the-docs

url: https://learningimages.github.io

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
